//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VetClinika.DBConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pet()
        {
            this.Priem = new HashSet<Priem>();
        }
    
        public int idPet { get; set; }
        public string namePet { get; set; }
        public Nullable<int> idGender { get; set; }
        public Nullable<int> idType { get; set; }
        public Nullable<int> Weight { get; set; }
        public Nullable<int> Height { get; set; }
    
        public virtual Gender Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Priem> Priem { get; set; }
        public virtual Type_Pet Type_Pet { get; set; }
        public virtual Type_Pet Type_Pet1 { get; set; }

    }
}
