//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VetClinika.DBConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Priem
    {
        public int idPriem { get; set; }
        public Nullable<int> idPet { get; set; }
        public Nullable<int> idVrach { get; set; }
        public Nullable<System.DateTime> DataPriem { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> isDelete { get; set; }
    
        public virtual Pet Pet { get; set; }
        public virtual Vrach Vrach { get; set; }
    }
}
