//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VetClinika.DBConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vrach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vrach()
        {
            this.Priem = new HashSet<Priem>();
        }
    
        public int idVrach { get; set; }
        public string famVrach { get; set; }
        public string nameVrach { get; set; }
        public string patronymicVrach { get; set; }
        public Nullable<int> idType { get; set; }
        public string login { get; set; }
        public string password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Priem> Priem { get; set; }
        public virtual Type_Vrach Type_Vrach { get; set; }
    }
}
